name: Lint PR title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
    branches: [main]

# Ensures linting for a previous PR title will be completed before linting a modified title.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      pull-requests: read
    outputs:
      error_message: ${{ steps.lint.outputs.error_message }}

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint
        env:
          GITHUB_TOKEN: ${{ github.token }}

  report-pr-title-lint-error:
    if: ${{ always() }}
    needs: lint-pr-title
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      pull-requests: write

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ needs.lint-pr-title.outputs.error_message != null }}
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! ðŸ‘‹

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ needs.lint-pr-title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved.
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ needs.lint-pr-title.outputs.error_message == null }}
        with:
          header: pr-title-lint-error
          delete: true
